// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // Robust environment variable detection for both Vite (client) and Cloudflare (server)
  const getEnv = (key: string) => {
    if (typeof import.meta !== 'undefined' && import.meta.env?.[`VITE_${key}`]) return import.meta.env[`VITE_${key}`];
    if (typeof process !== 'undefined' && process.env?.[`VITE_${key}`]) return process.env[`VITE_${key}`];
    if (typeof process !== 'undefined' && process.env?.[key]) return process.env[key];
    return undefined;
  };

  const SUPABASE_URL = getEnv('SUPABASE_URL');
  const SUPABASE_PUBLISHABLE_KEY = getEnv('SUPABASE_PUBLISHABLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const isServer = typeof window === 'undefined';
    if (isServer) {
      console.warn(`[Supabase Server] Missing environment variables. Rendering fallback.`);
      return null as any; // Return null on server to avoid crashing during SSR
    }
    
    // On client, returning a dummy client to prevent crash
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder', {
      auth: { persistSession: false }
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

